#!/usr/bin/python3
from sys import argv
import time
import os
def factors():
    start = time.time()
    with open(argv[1]) as f:
        for line in f:
            div = 2
            num = int(line)
            while True:
                end = time.time()
                if ((end - start) > 5):
                    os.system('pkill -f factors')
                #print("div = {}".format(div))
                #print("num = {}".format(num))
                if num % div == 0:
                    result = int(num / div)
                    print("{}={}*{}".format(num, result, div))
                    break
                else:
                    div += 1
    

factors()
